name: Java CI TP

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B clean test

      - name: Notify Telegram on success
        if: success()
        env:
          TELEGRAM_BOT_TOKEN: AAEYhBA7v-fgGBHUp7cOxZu_gMBLRsT-Yv0
          TELEGRAM_CHAT_ID: 7095802882
        run: |
          curl -X POST "https://api.telegram.org/bot${{ env.TELEGRAM_BOT_TOKEN }}/sendMessage" -d "chat_id=${{ env.TELEGRAM_CHAT_ID }}&text=Все ок"

      - name: Notify Telegram on failure
        if: failure()
        env:
          TELEGRAM_BOT_TOKEN: AAEYhBA7v-fgGBHUp7cOxZu_gMBLRsT-Yv0
          TELEGRAM_CHAT_ID: 7095802882
        run: |
          curl -X POST "https://api.telegram.org/bot${{ env.TELEGRAM_BOT_TOKEN }}/sendMessage" -d "chat_id=${{ env.TELEGRAM_CHAT_ID }}&text=Тесты не пройдены"