name: Java CI TP

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B clean test

      - name: Notify Telegram on success
        if: success()
        run: |
          curl -X POST "https://api.telegram.org/bot7095802882:AAEYhBA7v-fgGBHUp7cOxZu_gMBLRsT-Yv0/sendMessage" -d "chat_id=97446493&text=Все ок"

      - name: Notify Telegram on failure
        if: failure()
        run: |
          curl -X POST "https://api.telegram.org/bot7095802882:AAEYhBA7v-fgGBHUp7cOxZu_gMBLRsT-Yv0/sendMessage" -d "chat_id=97446493&text=Тесты не пройдены"